name: "Checkout with secrets"
description: "Checkout the repository with Google and AWS secrets"
inputs:
  aws-amplifyconfiguration:
    description: "The amplifyconfiguration.json file"
    required: true
  aws-awsconfiguration:
    description: "The awsconfiguration.json file"
    required: true
  google-services:
    description: "The google-services.json file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code with history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Copy Amplify configuration file to raw folder
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "amplifyconfiguration.json"
        json: ${{ inputs.aws-amplifyconfiguration }}
        dir: 'app/src/main/res/raw/'

    - name: Copy AWS configuration file to raw folder
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "awsconfiguration.json"
        json: ${{ inputs.aws-awsconfiguration }}
        dir: 'app/src/main/res/raw/'

    - name: Copy Firebase google-services.json file to app folder
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "google-services.json"
        json: ${{ inputs.google-services }}
        dir: 'app/'
