name: "Checkout with secrets"
description: "Checkout the repository with secrets"
inputs:
  aws-amplifyconfiguration:
    description: "The amplifyconfiguration.json file"
    required: true
  aws-awsconfiguration:
    description: "The awsconfiguration.json file"
    required: true
  google-services:
    description: "The google-services.json file"
    required: true
  graphhopper-api-key:
    description: "The Graphhopper API key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code with history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Copy Amplify configuration file to raw folder
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "amplifyconfiguration.json"
        json: ${{ inputs.aws-amplifyconfiguration }}
        dir: 'app/src/main/res/raw/'

    - name: Copy AWS configuration file to raw folder
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "awsconfiguration.json"
        json: ${{ inputs.aws-awsconfiguration }}
        dir: 'app/src/main/res/raw/'

    - name: Copy Graphhopper API key to local.properties
      shell: bash
      run: echo GRAPHHOPPER_API_KEY=\"${{ graphhopper-api-key }}\" > ./local.properties
