name: Verify, Build, Release, Deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout with secrets
        uses: ./.github/actions/checkout-with-secrets
        with:
          aws-amplifyconfiguration: ${{ secrets.AWS_AMPLIFY_CONFIGURATION }}
          aws-awsconfiguration: ${{ secrets.AWS_CONFIGURATION }}
          google-services: ${{ secrets.GOOGLE_SERVICES_JSON }}
          graphhopper-api-key: ${{ secrets.GRAPHHOPPER_API_KEY }}
          location-iq-api-key: ${{ secrets.LOCATION_IQ_API_KEY }}
          huki-routing-api-key: ${{ secrets.HUKI_ROUTING_API_KEY }}

      - name: Static code analysis
        run: ./gradlew lint detekt

  unit_tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout with secrets
        uses: ./.github/actions/checkout-with-secrets
        with:
          aws-amplifyconfiguration: ${{ secrets.AWS_AMPLIFY_CONFIGURATION }}
          aws-awsconfiguration: ${{ secrets.AWS_CONFIGURATION }}
          google-services: ${{ secrets.GOOGLE_SERVICES_JSON }}
          graphhopper-api-key: ${{ secrets.GRAPHHOPPER_API_KEY }}
          location-iq-api-key: ${{ secrets.LOCATION_IQ_API_KEY }}
          huki-routing-api-key: ${{ secrets.HUKI_ROUTING_API_KEY }}

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

  build_debug:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout with secrets
        uses: ./.github/actions/checkout-with-secrets
        with:
          aws-amplifyconfiguration: ${{ secrets.AWS_AMPLIFY_CONFIGURATION }}
          aws-awsconfiguration: ${{ secrets.AWS_CONFIGURATION }}
          google-services: ${{ secrets.GOOGLE_SERVICES_JSON }}
          graphhopper-api-key: ${{ secrets.GRAPHHOPPER_API_KEY }}
          location-iq-api-key: ${{ secrets.LOCATION_IQ_API_KEY }}
          huki-routing-api-key: ${{ secrets.HUKI_ROUTING_API_KEY }}

      - name: Verify debug build
        run: ./gradlew assembleDebug

  release:
    needs: [ lint, unit_tests, build_debug ]
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout with secrets
        uses: ./.github/actions/checkout-with-secrets
        with:
          aws-amplifyconfiguration: ${{ secrets.AWS_AMPLIFY_CONFIGURATION }}
          aws-awsconfiguration: ${{ secrets.AWS_CONFIGURATION }}
          google-services: ${{ secrets.GOOGLE_SERVICES_JSON }}
          graphhopper-api-key: ${{ secrets.GRAPHHOPPER_API_KEY }}
          location-iq-api-key: ${{ secrets.LOCATION_IQ_API_KEY }}
          huki-routing-api-key: ${{ secrets.HUKI_ROUTING_API_KEY }}

      - name: Generate Release Bundle AAB
        run: ./gradlew app:bundleRelease

      - name: Set release artifact names to ENV
        id: set_artifact_names
        run: |
          ARTIFACT_PATHNAME_AAB=$(ls app/build/outputs/bundle/release/*.aab | head -n 1)
          ARTIFACT_NAME_AAB=$(basename $ARTIFACT_PATHNAME_AAB)
          echo "ARTIFACT_PATHNAME_AAB is " ${ARTIFACT_PATHNAME_AAB}
          echo "ARTIFACT_NAME_AAB is " ${ARTIFACT_NAME_AAB}
          echo "ARTIFACT_PATHNAME_AAB=${ARTIFACT_PATHNAME_AAB}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME_AAB=${ARTIFACT_NAME_AAB}" >> $GITHUB_ENV

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT_NAME_AAB }}
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt

      - name: Publish to Google Play Store
        uses: r0adkll/upload-google-play@v1.0.17
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_PUBLISHER_SERVICE_ACCOUNT }}
          packageName: hu.mostoha.mobile.android.huki
          releaseFiles: ${{ env.ARTIFACT_PATHNAME_AAB }}
          track: internal
          whatsNewDirectory: app/src/main/assets/whatsnew/latest
          mappingFile: app/build/outputs/mapping/release/mapping.txt
